version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

volumes:
  db_data:
